label var jefe "Jefe de Hogar"
label var edad "Edad"
label var edad2 "Edad al cuadrado"
label var edad1217 "Edad 12 a 17"
label var edad1824 "Edad 18 a 24"
label var edad2540 "Edad 25 a 40"
label var edad4164 "Edad 41 a 64"
label var edad65 "Edad más de 65"
label var pric "=1 max nivel ed es primaria completa"
label var seci "=1 max nivel ed es secundaria incompleta"
label var secc "=1 max nivel ed es secundaria completa"
label var supi "=1 max nivel ed es superior incompleta"
label var supc "=1 max nivel ed es superior completa"
label var miembros "Cantidad de miembros"
label var miembros2 "Cantidad de miembros al cuadrado"
label var hombre "sexo - =1 hombre =2 mujer"
label var jj_edad "Edad jefe de hogar"
label var jj_edad2 "Edad jefe de hogar al cuadrado"
label var jj_pric "=1 jefe de hogar max nivel ed es primaria completa"
label var jj_seci "=1 jefe de hogar max nivel ed es secundaria incompleta"
label var jj_secc "=1 jefe de hogar max nivel ed es secundaria completa"
label var jj_supi "=1 jefe de hogar max nivel ed es superior incompleta"
label var jj_supc "=1 jefe de hogar max nivel ed es superior completa"
label var jj_hombre "=1 jefe de hogar hombre"
label var cc_mean_edad
label var hv_precaria 
label var hv_matpreca
label var hv_agua
label var hv_banio 
label var hv_cloacas 
label var hv_propieta 
label var hv_miemhabi 
label var reg2 "=1 Gran La Plata"
label var reg3 "=1 Bahía Blanca - Cerri"
label var reg4 "=1 Gran Rosario"
label var reg5 "=1 Gran Santa Fé"
label var reg6 "=1 Gran Paraná"
label var reg7 "=1 Posadas"
label var reg8 "=1 Gran Resistencia"
label var reg9 "=1 Cdro. Rivadavia - R.Tilly"
label var reg10 "=1 Gran Mendoza"
label var reg13 "=1 Gran Córdoba"
label var reg14 "=1 Concordia"
label var reg15 "=1 Formosa"
label var reg17 "=1 Neuquén - Plottier"
label var reg18 "=1 S. del Estero - La Banda"
label var reg19 "=1 Jujuy - Palpalá"
label var reg20 "=1 Río Gallegos"
label var reg22 "=1 Gran Catamarca"
label var reg23 "=1 Salta"
label var reg25 "=1 La Rioja"
label var reg26 "=1 San Luis - El Chorrillo"
label var reg27 "=1 Gran San Juan"
label var reg29 "=1 Gran Tucumán - T. Viejo"
label var reg30 "=1 Santa Rosa - Toay"
label var reg31 "=1 Ushuaia - Río Grande"
label var reg32 "=1 Ciudad de Bs As"
label var reg33 "=1 Partidos del GBA"
label var reg34 "=1 Mar del Plata - Batán"
label var reg36 "=1 Río Cuarto "
label var constant "Constante"
