quietly include "$path_programas\comando_atk"
quietly include "$path_programas\comando_fgt"
quietly include "$path_programas\comando_cuantiles"
quietly include "$path_programas\comando_gini"
quietly include "$path_programas\comando_theil"